### ISSUE TITLE
Most static methods in Quora and User really should be class methods

### ISSUE THREAD

**Issue by csu** [csu/pyquora#54]
We should fix this, but maintain the legacy API so things that currently use `pyquora` don't need to be rewritten. We can throw away the legacy support at a certain milestone, like v2.0 or something.

**Comment by csu** [comment]
Wait… never mind.

**Comment by rohithpr** [comment]
Well, you've closed this...but for future reference, what's the point of creating a new object for every question/answer they search? The user could just put the results into a list or something right?

**Comment by csu** [comment]
They don't have to create a new object for every question/answer? For example, see the test cases:

    q = Quora()
    stats1 = q.get_question_stats('If-space-is-3-dimensional-can-time-also-be-3-dimensional')
    stats2 = q.get_question_stats('I-need-a-summer-internship-but-I-dont-want-to-apply-because-theres-a-90-chance-Ill-get-rejected-What-should-I-do')
    stats3 = q.get_question_stats('What-are-the-best-intern-blog-posts-and-guides')
    stats4 = q.get_question_stats('What-data-structures-and-algorithms-should-one-implement-in-order-to-prepare-for-technical-interviews')
