### ISSUE TITLE
Question details doesn't work

### ISSUE THREAD

**Issue by csu** [csu/pyquora#59]
Try `Is-there-a-proof-of-the-Four-Color-Theorem-that-does-not-involve-substantial-computation`.

`GET: http://quora-api.herokuapp.com/questions/Is-there-a-proof-of-the-Four-Color-Theorem-that-does-not-involve-substantial-computation`

Output:
```json
{
  "answer_count": 4, 
  "answer_wiki": "<div class=\"hidden\" id=\"answer_wiki\"><div id=\"ld_ebgwib_28688\"><div id=\"__w2_sHb6iqm_wiki\"></div></div></div>", 
  "question_details": null, 
  "question_text": "Is there a proof of the Four Color Theorem that does not involve substantial computation?", 
  "topics": [
    "Science, Engineering, and Technology", 
    "Science", 
    "Formal Sciences", 
    "Mathematics"
  ], 
  "want_answers": 1
}
```

`question_details` is null, but the question has details on Quora.

**Comment by rohithpr** [comment]
Question details had a link in it...and some non-ascii characters!!

**Comment by csu** [comment]
Fixed
