### ISSUE TITLE
get_random_answers isn't particularly useful

### ISSUE THREAD

**Issue by csu** [csu/pyquora#62]
What possible use cases are there for get_random_answers? I don't think it's necessary/useful. Plus, we're importing `string` and `random` just for it.

**Comment by rohithpr** [comment]
In case someone wants a bunch of answers for data science projects or something, they could make use of it rather than having to specify a value manually. Ofc this could be done by the users themselves... Doesn't hurt to have an extra function right? :smile:

**Comment by csu** [comment]
It actually does kind of hurt to include it. If they want to use get_one_answer like this, they can write get_random_answerrs themselves, but we won't decide that for them. Libraries should be more general than that.

**Comment by rohithpr** [comment]
Um, oka! :p
