### ISSUE TITLE
nosetest imports `quora` from whatever is installed in the virtualenv and not the current working directory

### ISSUE THREAD

**Issue by rohithpr** [csu/pyquora#68]
I ran into a little something when I was writing tests and made changes to quora.py.
Those changes aren't useful as nosetest is importing quora from the venv.
Is this the expected behaviour or am I doing something wrong?

**Comment by csu** [comment]
Just don't have quora installed in the virtualenv for pyquora... it doesn't have itself as a dependency.

**Comment by rohithpr** [comment]
Tried it. Throws an error.
`ERROR: Failure: ImportError (No module named quora)`

**Comment by csu** [comment]
What directory are you running it from?

**Comment by rohithpr** [comment]
/quora/pyquora/tests

**Comment by csu** [comment]
Run it from pyquora.

**Comment by rohithpr** [comment]
Cool. Thanks.
