### ISSUE TITLE
Quora is blocking scrapers

### ISSUE THREAD

**Issue by rohithpr** [csu/pyquora#74]
As I've stated [here](https://github.com/csu/quora-api/issues/33#issuecomment-109320196), quora is blocking some (all?) scripts.

```python
from bs4 import BeautifulSoup
import requests

url = 'http://www.quora.com/search?q=flowers'
soup = BeautifulSoup(requests.get(url).text)
print soup
```

```HTML
<html>
  <head>
    <title>503 Service Unavailable</title>
  </head>
  <body>
    <h1>503 Service Unavailable</h1>
      The server is currently unavailable. Please try again at a later time.<br/><br/>
      Our automated scripts have detected a possible scraper. If you feel we have made an error, please email info@quora.com. Sorry for the inconvenience. Thanks.


  </body>
</html>
```

**Comment by csu** [comment]
Ah, interesting. We could spoof a user agent so we look like a browser. We should also consider switching to PhantomJS or Selenium then.

**Comment by csu** [comment]
User agents is an easy fix. See: http://stackoverflow.com/questions/10606133/how-to-send-user-agent-in-requests-library-in-python

**Comment by rohithpr** [comment]
I tried it before raising the issue! :p no use

**Comment by csu** [comment]
Darn. I guess we should rewrite in PhantomJS or Selenium then.

**Comment by csu** [comment]
Are we still having this problem?

**Comment by rohithpr** [comment]
This issue seems to be specific to search! All the existing functions work just fine.

**Comment by csu** [comment]
Closing this because it seems like a problem with just search. Reopen if need be.
