### ISSUE TITLE
how to get all the answers of a question

### ISSUE THREAD

**Issue by wdfsinap** [csu/pyquora#77]
using Quora.get_one_answer('6hARL') can only get one answer for a question.
I mean how to get all the answers of a question?
thanks

**Comment by csu** [comment]
```
# Get the latest answers from a question
latest_answers = Quora.get_latest_answers('what-is-python')
```

It's right in the README: https://github.com/csu/pyquora#answer-statistics. Please actually read the README instead of continuously opening issues requesting information that is readily accessible from it.

**Comment by wdfsinap** [comment]
are you sure you understand my question? Quora.get_latest_answers only get the latest answers, not all the answers of a question. you can try by yourself.

**Comment by csu** [comment]
Then the functionality you're asking for doesn't exist.
