### ISSUE TITLE
"Want Answers" Causes TestQuestionStatistics to Fail

### ISSUE THREAD

**Issue by benjamincongdon** [csu/pyquora#85]
"Want Answers" has become "Follow", so line 166 in `quora.py` fails, and results in an empty dict to be returned.

Offending line:
`want_answers = soup.find('span', attrs={'class' : 'count'}).string`

**Comment by benjamincongdon** [comment]
Actually, it appears there are multiple `span`s with class `count`, so `soup.find()` won't work.

**Comment by csu** [comment]
Thanks for filing the issue. I looked into this and it looks like this information isn't available anymore. `pyquora` will scrape without being logged in and it looks like when you're not logged in, this information isn't even displayed (e.g. try loading https://www.quora.com/When-should-I-fire-my-cofounder?share=1 while logged out or in a private browsing window). I'll just remove the field for now.

**Comment by benjamincongdon** [comment]
Ah. Thanks for the clarification.

**Comment by csu** [comment]
Build and tests are passing again.
